sonar.projectKey=f1Costa_devops-openshift-rabbitmq
sonar.organization=flipxx25
sonar.sources=app
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=test-results.xml
sonar.qualitygate.wait=true
