sonar.projectKey=devops-api
sonar.projectName=DevOps Reference API
sonar.projectVersion=1.0

# Fontes e testes
sonar.sources=app
sonar.tests=tests
sonar.language=python

# Cobertura
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=test-results.xml

# Exclusões
sonar.exclusions=**/__pycache__/**,**/*.pyc,**/migrations/**

# Quality Gate — bloqueia o pipeline se não atingir
sonar.qualitygate.wait=true
